var draftedPlayers = [
  "Cole Palmer",
  "Bukayo Saka",
  "Florian Wirtz",
  "Ollie Watkins",
  "Viktor Gyökeres",
  "Alexander Isak",
  "Jarrod Bowen",
  "Bruno Borges Fernandes",
  "Chris Wood",
  "João Pedro Junqueira de Jesus",
  "Benjamin Sesko",
  "Bryan Mbeumo",
  "Phil Foden",
  "Daichi Kamada",
  "Matheus Santos Carneiro da Cunha",
  "Hugo Ekitiké",
  "Jeremie Frimpong",
  "Joško Gvardiol",
  "Cody Gakpo",
  "Omar Marmoush",
  "Martin Ødegaard",
  "Rayan Aït-Nouri",
  "Jean-Philippe Mateta",
  "Dominic Solanke-Mitchell",
  "Rayan Cherki",
  "Yoane Wissa",
  "Nicolas Jackson",
  "Pedro Lomba Neto",
  "Declan Rice",
  "Jørgen Strand Larsen",
  "Gabriel dos Santos Magalhães",
  "Francisco Evanilson de Lima Barbosa",
  "Liam Delap",
  "Eberechi Eze",
  "Anthony Elanga",
  "Anthony Gordon",
  "Marc Guiu Paz",
  "Antoine Semenyo",
  "Danny Welbeck",
  "Morgan Rogers",
  "Mitoma Kaoru",
  "Mohammed Kudus",
  "Dominik Szoboszlai",
  "Milos Kerkez",
  "Raúl Jiménez Rodríguez",
  "Igor Thiago Nascimento Rodrigues",
  "Morgan Gibbs-White",
  "Ismaïla Sarr",
  "Norberto Bercique Gomes Betuncal",
  "Simon Adingra",
  "Noni Madueke",
  "Jack Grealish",
  "Thierno Barry",
  "Niclas Füllkrug",
  "Georginio Rutter",
  "Iliman Ndiaye",
  "Mikel Merino Zazón",
  "Virgil van Dijk",
  "Jamie Bynoe-Gittens",
  "Rodrigo Muniz Carvalho",
  "Leandro Trossard",
  "Brennan Johnson",
  "Gabriel Martinelli Silva",
  "Tijjani Reijnders",
  "Pedro Porro Sauceda",
  "Joël Piroe",
  "Micky van de Ven",
  "Enzo Fernández",
  "William Saliba",
  "Jhon Arias",
  "Kai Havertz",
  "Amad Diallo",
  "Donyell Malen",
  "Leny Yoro",
  "Rio Ngumoha",
  "Daniel Muñoz Mejía",
  "Alisson Becker",
  "Marc Cucurella Saseta",
  "Lucas Tolentino Coelho de Lima",
  "Justin Kluivert",
  "Ezri Konsa Ngoyo",
  "Nikola Milenković",
  "Kyle Walker",
  "runo Guimarães Rodriguez Moura",
  "Rodrigo 'Rodri' Hernandez Cascante",
  "Adrien Truffert",
  "Evann Guessand",
  "David Raya Martín",
  "Robert Lynch Sánchez",
  "Cristian Romero",
  "Callum Wilson",
  "Yankuba Minteh",
  "João Maria Lobo Alves Palhares Costa Palhinha Gonçalves",
  "James Ward-Prowse",
  "Murillo Costa dos Santos",
  "Patrick Dorgu",
  "Andrew Robertson",
  "Marc Guéhi",
  "Martín Zubimendi Ibáñez",
  "Alexis Mac Allister",
  "Jacob Murphy",
  "Aaron Ramsey",
  "James Tarkowski",
  "Fabian Schär",
  "Myles Lewis-Skellys",
  "Maxence Lacroix",
  "Destiny Udogie",
  "Kieran Trippier",
  "Dan Burn",
  "Neco Williams",
  "Lewis Hall",
  "Ola Aina",
  "André Onana",
  "Jordan Pickford",
  "Moisés Caicedo Corozo",
  "İlkay Gündoğan",
  "Eddie Nketiah",
  "Matz Sels",
  "Carlos Baleba",
  "Ibrahima Konaté",
];
